/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'account/manageAccount': RouteRecordInfo<'account/manageAccount', '/account/manageAccount', Record<never, never>, Record<never, never>>,
    'account/manageAccount/account': RouteRecordInfo<'account/manageAccount/account', '/account/manageAccount/account', Record<never, never>, Record<never, never>>,
    'account/manageAccount/changePwd': RouteRecordInfo<'account/manageAccount/changePwd', '/account/manageAccount/changePwd', Record<never, never>, Record<never, never>>,
    'account/manageAccount/shopHistory': RouteRecordInfo<'account/manageAccount/shopHistory', '/account/manageAccount/shopHistory', Record<never, never>, Record<never, never>>,
    'account/shopping/checkout': RouteRecordInfo<'account/shopping/checkout', '/account/shopping/checkout', Record<never, never>, Record<never, never>>,
    'account/shopping/checkoutComplete': RouteRecordInfo<'account/shopping/checkoutComplete', '/account/shopping/checkoutComplete', Record<never, never>, Record<never, never>>,
    'account/shopping/shoppingCar': RouteRecordInfo<'account/shopping/shoppingCar', '/account/shopping/shoppingCar', Record<never, never>, Record<never, never>>,
    'account/signout': RouteRecordInfo<'account/signout', '/account/signout', Record<never, never>, Record<never, never>>,
    'admin/account/accountMsg': RouteRecordInfo<'admin/account/accountMsg', '/admin/account/accountMsg', Record<never, never>, Record<never, never>>,
    'admin/account/accountShow': RouteRecordInfo<'admin/account/accountShow', '/admin/account/accountShow', Record<never, never>, Record<never, never>>,
    'admin/admin': RouteRecordInfo<'admin/admin', '/admin/admin', Record<never, never>, Record<never, never>>,
    'admin/leaveReply/leaveReplyMsg': RouteRecordInfo<'admin/leaveReply/leaveReplyMsg', '/admin/leaveReply/leaveReplyMsg', Record<never, never>, Record<never, never>>,
    'admin/order/orderMsg': RouteRecordInfo<'admin/order/orderMsg', '/admin/order/orderMsg', Record<never, never>, Record<never, never>>,
    'admin/order/orderShow': RouteRecordInfo<'admin/order/orderShow', '/admin/order/orderShow', Record<never, never>, Record<never, never>>,
    'admin/product/productMag': RouteRecordInfo<'admin/product/productMag', '/admin/product/productMag', Record<never, never>, Record<never, never>>,
    'admin/product/productShow': RouteRecordInfo<'admin/product/productShow', '/admin/product/productShow', Record<never, never>, Record<never, never>>,
    'HomeView': RouteRecordInfo<'HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    'item': RouteRecordInfo<'item', '/item', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'NotFound': RouteRecordInfo<'NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    'search': RouteRecordInfo<'search', '/search', Record<never, never>, Record<never, never>>,
    'signUp': RouteRecordInfo<'signUp', '/signUp', Record<never, never>, Record<never, never>>,
  }
}
